#!/bin/sh
# SPDX-FileCopyrightText: 2024 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0
set -eu

latest_day() {
	find . -type d -name 'day[0-9][0-9]' -prune \
		| sed 's|./day||' | sort -n | tail -n 1
}

if [ "$#" -eq 0 ]
then
	set -- "$(latest_day)"
fi

if [ "$#" -ne 1 ]
then
	printf 'Usage: %s [NUM]\n' "${0##*/}" >&2
	exit 2
fi

set -- "$(printf '%02d' "$1")"

# Create the required directory and files
day_dir="day$1"
day_file="$day_dir/day$1.txt"
input_file="$day_dir/input"
solution_file="$day_dir/solution"
mkdir -p "$day_dir"
touch "$day_file" "$input_file" "$solution_file"
chmod +x "$solution_file"

# Open the files for editing
vim -p "$day_file" "$solution_file" "$input_file"
